### ISSUE TITLE
Link crates.io page somewhere in repo

### ISSUE THREAD

**Issue by GeckoEidechse** [barnabwhy/sourcepak-rs#2]
Either in README with a clickable badge or in the sidebar (or both) in order to more easily find the corresponding crate.

Example: https://github.com/GeckoEidechse/mdbook-gitbook?tab=readme-ov-file#mdbook-gitbook

Not really a big deal, just nice to have ;)

**Comment by barnabwhy** [comment]
fixed in 47d46f5
